security:
  enable_authenticator_manager: true

  # Configuration des hacheurs de mot de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\User:
      algorithm: auto

  # Configuration du fournisseur de l'utilisateur
  providers:
    # Fournisseur utilisé pour recharger l'utilisateur à partir de la session et d'autres fonctionnalités
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    # Firewall pour le mode développement
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

  access_control:
     - { path: ^/api/login, roles: PUBLIC_ACCESS }


when@test:
  security:
    # Configuration des hacheurs de mot de passe pour les tests
    password_hashers:
      App\Entity\User:
        algorithm: auto
        cost: 4 # Valeur la plus basse possible pour bcrypt
        time_cost: 3 # Valeur la plus basse possible pour argon
        memory_cost: 10 # Valeur la plus basse possible pour argon