controllers:
    resource: ../src/Controller/
    type: annotation

default:
    path: /{req}
    defaults: {_controller : 'App\Controller\AppController::index'}
    requirements: 
        req: ".+"



api_login_check:
    path: ^/api/login_check